name: Build project

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  buildForAllPlatformsWindows:
    name: ${{ matrix.targetPlatform }} on ${{ matrix.unityVersion }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - project
        unityVersion:
          - 2023.2.3f1
        targetPlatform:
          - Android # Build an Android app.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-windows-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-windows-
            Library-

      - name: Build
        uses: ./
        id: build-1
        continue-on-error: true
        timeout-minutes: 30
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildName: 'SBA Mod Engine'
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: -profile SomeProfile -someBoolean -someValue exampleValue
          allowDirtyBuild: true

      - uses: actions/upload-artifact@v4
        with:
          name: Build ${{ matrix.targetPlatform }} on Windows (${{ matrix.unityVersion }})
          path: build
          retention-days: 14